flaskr/blueprints/base.py
from flask import Blueprint, render_template,redirect,url_for,request,session,flash
from flaskr.models import Administrator,Card_id,User

bp = Blueprint('base', __name__,url_prefix='/')


#主菜单
@bp.route("/")
def base():
    if 'logged_in' in session and session["logged_in"]==True:  # 检查登录状态
        return redirect(url_for('base.dashboard'))  # 已登录，跳转到仪表盘
    return redirect(url_for('base.login'))  # 未登录，跳转到登录页


# 管理登录
@bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        # 从数据库中查找管理
        admin = Administrator.query.filter_by(username=username).first()

        if admin and admin.check_password(password):
            session['admin_id'] = admin.id  # 登录成功，设置用户会话
            session['logged_in'] = True
            flash('登录成功！', 'success')
            return redirect(url_for('base.dashboard'))  # 跳转到仪表盘
        else:
            flash('用户名或密码错误，请重试。', 'danger')

    return render_template("login.html")  # 如果是 GET 请求，返回登录页面

# 仪表盘


@bp.route('/dashboard')
def dashboard():
    # 手动检查用户是否登录
    if 'logged_in' not in session:
        flash('请先登录。', 'warning')
        return redirect(url_for('base.login'))  # 重定向到登录页面

    user_count = 100  # 示例数据
    card_count = 200  # 示例数据
    return render_template('dashboard.html', user_count=user_count, card_count=card_count)




# 卡片管理页面
@bp.route('/cards')
def card_list():
    page = request.args.get('page', 1, type=int)  # 获取当前页码，默认为1
    per_page = 10  # 每页显示的条数

    # 使用 paginate 方法查询卡片数据，注意模型名和数据库的连接
    pagination = Card_id.query.paginate(page=page, per_page=per_page, error_out=False)

    cards = pagination.items  # 获取当前页的卡片数据
    return render_template('cards.html', cards=cards, pagination=pagination)

#用户管理
@bp.route('/user')
def user_list():
    page = request.args.get('page', 1, type=int)
    per_page = 10

    pagination = User.query.paginate(page=page, per_page=per_page, error_out=False)

    users = pagination.items
    return render_template('user.html', users=users, pagination=pagination)

flaskr/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}后台管理{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{{ url_for('base.dashboard') }}">首页(仪表盘)</a></li>
                <li><a href="{{ url_for('base.user_list') }}">用户管理</a></li>
                <li><a href="{{ url_for('base.card_list') }}">卡片管理</a></li>
                <li><a href="{{ url_for('base.login') }}">登录</a></li>
            </ul>
        </nav>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

<!--    <footer>-->
<!--        <p>&copy; 2024 后台管理系统</p>-->
<!--    </footer>-->

    <script src="{{ url_for('static', filename='javascript/base.js') }}"></script>
</body>
</html>

flaskr/templates/cards.html
<!-- templates/dashboard.html -->
{% extends "base.html" %}

{% block title %}卡片管理{% endblock %}

{% block content %}
<!-- 卡片列表 -->
    <table border="1">
        <tr>
            <th>ID</th>
            <th>Image Path</th>
            <th>Name</th>
            <th>Gender</th>
            <th>Nation</th>
            <th>Birthday</th>
            <th>Address</th>
            <th>ID Number</th>
        </tr>
        {% for card in cards %}
        <tr>
            <td>{{ card.id }}</td>
            <td>{{ card.image_path }}</td>
            <td>{{ card.name }}</td>
            <td>{{ card.gender }}</td>
            <td>{{ card.nation }}</td>
            <td>{{ card.birthday }}</td>
            <td>{{ card.address }}</td>
            <td>{{ card.id_number }}</td>
        </tr>
        {% endfor %}
    </table>

    <!-- 分页导航 -->
    <div class="pagination-bar">
        <ul>
            {% if pagination.has_prev %}
                <li><a href="{{ url_for('base.card_list', page=pagination.prev_num) }}">Previous</a></li>
            {% endif %}
            {% for page_num in pagination.iter_pages() %}
                {% if page_num %}
                    <li><a href="{{ url_for('base.card_list', page=page_num) }}">{{ page_num }}</a></li>
                {% endif %}
            {% endfor %}
            {% if pagination.has_next %}
                <li><a href="{{ url_for('base.card_list', page=pagination.next_num) }}">Next</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}

flaskr/templates/dashboard.html
<!-- templates/dashboard.html -->
{% extends "base.html" %}

{% block title %}仪表盘{% endblock %}

{% block content %}
<div>
    <h2>主菜单</h2>
    <p>欢迎</p>

</div>
{% endblock %}

flaskr/templates/edit.html
<!-- templates/edit_user.html -->
{% extends "base.html" %}

{% block title %}编辑用户{% endblock %}

{% block content %}
<div>
    <h2>编辑用户</h2>
    <form method="POST" action="{{ url_for('edit_user', user_id=user.id) }}">
        <label for="username">用户名:</label>
        <input type="text" name="username" id="username" value="{{ user.username }}" required><br>

        <label for="email">邮箱:</label>
        <input type="email" name="email" id="email" value="{{ user.email }}" required><br>

        <button type="submit">保存</button>
    </form>
</div>
{% endblock %}

flaskr/templates/login.html
<!-- templates/login.html -->
{% extends "base.html" %}

{% block title %}登录{% endblock %}

{% block content %}
<div>
    <h2>登录</h2>
    <form method="POST" action="{{ url_for('base.login') }}">
        <label for="username">用户名:</label>
        <input type="text" name="username" id="username" required><br>

        <label for="password">密码:</label>
        <input type="password" name="password" id="password" required><br>

        <button type="submit">登录</button>
    </form>
</div>
{% endblock %}

flaskr/templates/user.html
<!-- templates/dashboard.html -->
{% extends "base.html" %}

{% block title %}卡片管理{% endblock %}

{% block content %}
<!-- 卡片列表 -->
    <table border="1">
        <tr>
            <th>ID</th>
            <th>Username</th>
            <th>email</th>

        </tr>
        {% for user in users %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.email }}</td>

        </tr>
        {% endfor %}
    </table>

    <!-- 分页导航 -->
    <div class="pagination-bar">
        <ul>
            {% if pagination.has_prev %}
                <li><a href="{{ url_for('base.user_list', page=pagination.prev_num) }}">Previous</a></li>
            {% endif %}
            {% for page_num in pagination.iter_pages() %}
                {% if page_num %}
                    <li><a href="{{ url_for('base.user_list', page=page_num) }}">{{ page_num }}</a></li>
                {% endif %}
            {% endfor %}
            {% if pagination.has_next %}
                <li><a href="{{ url_for('base.user_list', page=pagination.next_num) }}">Next</a></li>
            {% endif %}
        </ul>
    </div>
{% endblock %}